---

templates:
  gain:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/amp.so
      id: 1048
  compressor:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/ZamComp-ladspa.so
    config:
      Knee: 15
      Threshold: -20
      Makeup: 0
      Sidechain: 1
  gate:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/ZamGate-ladspa.so
  delay:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/delay_1898.so
      id: 1899

chains:
  remove_squelch_tail:
    channels: 1
    state:
      - gate:*
    forward:
      in_1:
        - delay:Input
        - gate:Sidechain Input
    nodes:
      - name: delay
        template: delay
        config:
          Delay Time (s): .1
          Max Delay (s): .2
        link:
          Output: gate:Audio Input 1

      - name: gate
        template: gate
        forward:
          Audio Output 1: remove_squelch_tail:out_1

domain:
  config:
    sample_rate: 48000
    buffer_size: 1024
    threads: 4
  nodes:
    - name: jack
      class: pulsar::jackaudio::node
      config:
        client_name: pulsar
      inputs: [ left_out, right_out, demod_out, mono_out ]
      outputs: [ right_in, left_in, demod_in ]
      link:
        right_in: jack:right_out
        left_in: comp_left:*
        right_in: comp_right:*
        demod_in: tail_eater:in_1

    - name: tail_eater
      chain: remove_squelch_tail
      link:
        out_1: jack:demod_out

    - name: comp_left
      template: compressor
      link: gain_left1

    - name: comp_right
      template: compressor
      link: gain_right1

    - name: gain_left1
      template: gain
      plugin:
        filename: /usr/lib/ladspa/amp.so
      config:
        Gain: .5
      link:
        Output:
          - gain_left2
          - jack:mono_out

    - name: gain_right1
      template: gain
      config:
        Gain: .5
      link:
        Output:
          - gain_right2
          - jack:mono_out

    - name: gain_left2
      template: gain
      config:
        Gain: 2
      link:
        Output: jack:left_out

    - name: gain_right2
      template: gain
      config:
        Gain: 2
      link:
        Output: jack:right_out
