---

templates:
  gain:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/amp.so
      id: 1048
  compressor:
      class: pulsar::ladspa::node
      plugin:
        filename: /usr/lib/ladspa/ZamComp-ladspa.so
      config:
        Knee: 15
        Threshold: -20
        Makeup: 6

domain:
  config:
    sample_rate: 48000
    buffer_size: 1024
    threads: 4
  nodes:
    - name: jack
      class: pulsar::jackaudio::node
      config:
        client_name: pulsar
      inputs: [ left_out, right_out ]
      outputs: [ right_in, left_in ]
      connect:
        left_in: comp_left:Audio Input 1
        right_in: comp_right:Audio Input 1

    - name: comp_left
      template: compressor
      connect:
        Audio Output 1: gain_left1:Input

    - name: comp_right
      template: compressor
      connect:
        Audio Output 1: gain_right1:Input

    - name: gain_left1
      template: gain
      plugin:
        filename: /usr/lib/ladspa/amp.so
      config:
        Gain: .5
      connect:
        Output: gain_left2:Input

    - name: gain_right1
      template: gain
      config:
        Gain: .5
      connect:
        Output: gain_right2:Input

    - name: gain_left2
      template: gain
      config:
        Gain: 2
      connect:
        Output: jack:left_out

    - name: gain_right2
      template: gain
      config:
        Gain: 2
      connect:
        Output: jack:right_out
