---

templates:
  gain:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/amp.so
      id: 1048
  compressor:
      class: pulsar::ladspa::node
      plugin:
        filename: /usr/lib/ladspa/ZamComp-ladspa.so
      config:
        Knee: 15
        Threshold: -20
        Makeup: 0
        Sidechain: 1

chains:
  remove_squelch_tail:
    inputs: [ out ]
    outputs: [ in ]
    connect:
      in:
        - delay:Input
        - gate:Sidechain Input
    nodes:
      - name: delay
        class: pulsar::ladspa::node
        plugin:
          filename: /usr/lib/ladspa/delay_1898.so
          id: 1898
        config:
          Delay Time (s): .1
          Max Delay (s): .2
        connect:
          Output: gate:Audio Input 1

      - name: gate
        class: pulsar::ladspa::node
        plugin:
          filename: /usr/lib/ladspa/ZamGate-ladspa.so
        connect:
          Audio Output 1: remove_squelch_tail:out

domain:
  config:
    sample_rate: 48000
    buffer_size: 1024
    threads: 4
  nodes:
    - name: jack
      class: pulsar::jackaudio::node
      config:
        client_name: pulsar
      inputs: [ left_out, right_out, mono_out, demod_out ]
      outputs: [ right_in, left_in, demod_in ]
      connect:
        left_in: comp_left:*
        right_in: comp_right:*
        # demod_in: tail_eater:in

    - name: comp_left
      template: compressor
      connect: gain_left1

    - name: comp_right
      template: compressor
      connect: gain_right1

    - name: gain_left1
      template: gain
      plugin:
        filename: /usr/lib/ladspa/amp.so
      config:
        Gain: .5
      connect: gain_left2

    - name: gain_right1
      template: gain
      config:
        Gain: .5
      connect: gain_right2

    - name: gain_left2
      template: gain
      config:
        Gain: 2
      connect:
        Output: jack:left_out
        # Output: mono_gain

    - name: gain_right2
      template: gain
      config:
        Gain: 2
      connect:
        Output: jack:right_out
        # Output: mono_gain

    - name: mono_gain
      template: gain
      config:
        Gain: .5
      connect:
        # Output: jack:mono_out

    - name: tail_eater
      chain: remove_squelch_tail
      connect:
        in: jack:demod_out
